### ISSUE TITLE
Make it easier to customize backup names

### ISSUE THREAD

**Issue by NeoIsRecursive** [itiden/statamic-backup#36]
As of now you have to create a new `BackupRepository` just to change how the name is set, no bueno...

I have been playing around with the idea of storing backups in some sort of yaml file, which would open up more possibilities with meta data and not having to compute backup sizes etc. every time it's accessed.

something like this:

```yml
backups:
    ...
    timestamp: 
       name: string,
       size: whatever
       disk?: string
       path: string
```
